// The SquirtRag: published issues and the articles inside them.
//
// Issues are generated by the publish job and committed to the repo, which
// triggers a deploy. Nothing here calls an API: pages read what was committed.

import fs from 'node:fs';
import path from 'node:path';
import { SIGN_OFF_SEED, type ArticleId } from '../config/style-guide.ts';

export type Article = {
  id: ArticleId;
  slug: string;
  category: string;
  headline: string;
  deck: string;
  body: string[];
  /** Minutes, computed from the body at publish time. */
  readTime: number;
  /** Set when a correction changed this article after publication. */
  updatedAt?: string;
  retracted?: boolean;
  /** True when validation failed twice and the template wrote this instead. */
  fromTemplate?: boolean;
};

/**
 * The facts as they stood at publication.
 *
 * Stored because the corrections check has to compare what was published
 * against what the stats say now, and recovering that by parsing numbers back
 * out of prose is exactly the fragility this pipeline exists to avoid.
 */
export type IssueSnapshot = {
  shart: { manager: string; team: string; points: number };
  managerOfWeek: { manager: string; team: string; points: number };
  results: { matchupId: number; winner: string; awayPoints: number; homePoints: number }[];
};

export type Issue = {
  week: number;
  season: string;
  publishedAt: string;
  updatedAt?: string;
  /** The sign off used by the Shart story, stored so the next one tops it. */
  signOff?: string;
  snapshot?: IssueSnapshot;
  articles: Article[];
};

export type Retraction = {
  week: number;
  queuedAt: string;
  reason: string;
  was: string;
  now: string;
};

const DIR = path.join('data', 'rag');

export const slugFor = (headline: string) =>
  headline
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 60);

export const readTimeOf = (body: string[]) =>
  Math.max(1, Math.round(body.join(' ').split(/\s+/).length / 220));

export function issuePath(week: number) {
  return path.join(DIR, `week-${week}.json`);
}

export function readIssue(week: number): Issue | null {
  try {
    return JSON.parse(fs.readFileSync(issuePath(week), 'utf8')) as Issue;
  } catch {
    return null;
  }
}

export function writeIssue(issue: Issue) {
  fs.mkdirSync(DIR, { recursive: true });
  const sorted = {
    articles: issue.articles,
    publishedAt: issue.publishedAt,
    season: issue.season,
    signOff: issue.signOff,
    updatedAt: issue.updatedAt,
    week: issue.week,
  };
  fs.writeFileSync(issuePath(issue.week), JSON.stringify(sorted, null, 1));
}

export function publishedWeeks(): number[] {
  try {
    return fs
      .readdirSync(DIR)
      .map((file) => Number(file.match(/^week-(\d+)\.json$/)?.[1]))
      .filter((week): week is number => Number.isFinite(week))
      .sort((a, b) => a - b);
  } catch {
    return [];
  }
}

/**
 * The sign off worth storing for a Shart story.
 *
 * The field the writer returns cannot be trusted on its own. Week 1 closed its
 * body with a real escalation, "grab every pitcher in the building, line them
 * up", and still returned the bare seed in the signOff field. Storing the field
 * meant the next week would be handed the seed and asked to top nothing, which
 * breaks the escalation the brief asks for, permanently, from week one.
 *
 * The body is what actually published, so a closing paragraph that ends with
 * the required words beats a thinner field.
 */
export function signOffFrom(candidate: { body: string[]; signOff?: string }): string | undefined {
  const field = candidate.signOff?.trim();
  const tail = candidate.body[candidate.body.length - 1]?.trim() ?? '';

  if (tail.endsWith(SIGN_OFF_SEED) && tail.length > (field?.length ?? 0)) {
    // Capped so a runaway closing paragraph does not become the line the next
    // week has to beat. Trimmed to a word boundary rather than mid word.
    return tail.length <= 400 ? tail : tail.slice(-400).replace(/^\S*\s+/, '');
  }

  return field || undefined;
}

/** Every sign off used so far, oldest first, fed back so the next one escalates. */
export function signOffHistory(): string[] {
  return publishedWeeks()
    .map((week) => readIssue(week)?.signOff)
    .filter((line): line is string => Boolean(line));
}

/**
 * Queued retractions, read by the next issue.
 *
 * Declared here rather than beside the Retraction type because it reads DIR,
 * and a const is block scoped rather than hoisted: placing it above DIR threw
 * at module load in the temporal dead zone.
 */
const RETRACTIONS = path.join(DIR, 'retractions.json');

export function readRetractions(): Retraction[] {
  try {
    return JSON.parse(fs.readFileSync(RETRACTIONS, 'utf8')) as Retraction[];
  } catch {
    return [];
  }
}

export function queueRetraction(entry: Retraction) {
  const all = readRetractions();
  all.push(entry);
  fs.mkdirSync(DIR, { recursive: true });
  fs.writeFileSync(RETRACTIONS, JSON.stringify(all, null, 1));
}

/** Tuesdays at 9:00 AM Central, per Brief Section 3. */
export function publishDateFor(week: number, seasonStart = '2026-09-09'): Date {
  // Week 1 runs the Tuesday after the season opens.
  const start = new Date(`${seasonStart}T00:00:00Z`);
  const firstTuesday = new Date(start);
  while (firstTuesday.getUTCDay() !== 2) firstTuesday.setUTCDate(firstTuesday.getUTCDate() + 1);
  const publish = new Date(firstTuesday);
  publish.setUTCDate(publish.getUTCDate() + (week - 1) * 7);
  return publish;
}
